reserved = {
    "str": "STR",
    "num": "NUM",
    "bool": "BOOL",
    "list": "LIST",
    "func": "FUNC",
    "return": "RETURN",
    "if": "IF",
    "else": "ELSE",
    "loop": "LOOP",
    "in": "IN",
    "range": "RANGE",
    "console": "CONSOLE",
    "true": "TRUE",
    "false": "FALSE",
    "#start": "START",
    "#end": "END",
}

tokens = [
    "ID",
    "NUMBER",
    "STRING",
    # operadores
    "PLUS",
    "MINUS",
    "MULTIPLY",
    "DIVIDE",
    "AND",
    "OR",
    "NOT",
    "LT",
    "GT",
    "LE",
    "GE",
    "EQ",
    "NE",
    "ASSIGN",
    # delimitadores
    "LPAREN",
    "RPAREN",
    "LBRACE",
    "RBRACE",
    "COMMA",
    "LBRACKET",
    "RBRACKET",
    "DOT",
] + list(reserved.values())
